<a href="https://colab.research.google.com/github/pswami12/DataScienceFiles/blob/main/Class_3_AIDL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
V0 = torch.tensor(1.3)
V1 = torch.tensor([1.,2.,3.])
V2 = torch.tensor([[1.,2.],[4.,5.]])
print(f'{V0}, {V1}, {V2}')

1.2999999523162842, tensor([1., 2., 3.]), tensor([[1., 2.],
        [4., 5.]])


In [3]:
import numpy as np
V0 = np.array(1.3)
V1 = np.array([1.,2.,3.])
V2 = np.array([[1.,2.],[4.,5.]])
print(f'{V0}, {V1}, {V2}')

1.3, [1. 2. 3.], [[1. 2.]
 [4. 5.]]


In [4]:
numpy_array = np.array([1,2,3])
numpy_array

array([1, 2, 3])

In [5]:
numpy_array*4

array([ 4,  8, 12])

In [6]:
t1 = torch.Tensor(numpy_array)
t1
#Constructor - same as torch.FloatTensor
#Uses a default float32 tensor, can be changed
#all other tensor inherits from this main tensor class
#torch.tensor(data, dtype=None, device=None, requires_grad =False) -> Tensor

tensor([1., 2., 3.])

In [7]:
t2 = torch.tensor(numpy_array)
t2
#Factory function
#produces a new tensor with same type
#does not share underlying memory with numpy
#always copies the data
#torch.tensor(x) is equivalent to x.clone().detach()
#recommend to use

tensor([1, 2, 3])

In [8]:
t3 = torch.as_tensor(numpy_array)
t3
#produce a new tensor with same dtype
#share underlying memory with numpy, changing one will change other
#can accepts any array like python data structure
#always try to avoid copies of the data (like using numpy's stored values directly)
#Have to manually add required_grad_() function, or doesn't support requires_grad flag
#recommend to use

tensor([1, 2, 3])

In [9]:
t4 = torch.from_numpy(numpy_array)
t4
#Factory function
#produces a new tensor with same dtype
#can accept only numpy arrays
#share underlying memory with numpy, changing one will change other

tensor([1, 2, 3])

In [10]:
numpy_array*=4
t1,t2,t3,t4

(tensor([1., 2., 3.]),
 tensor([1, 2, 3]),
 tensor([ 4,  8, 12]),
 tensor([ 4,  8, 12]))

In [11]:
data = torch.tensor([[1,2,3],[4,5,6]])
data[1, 0], data[0, : 2]

(tensor(4), tensor([1, 2]))

In [12]:
from torch.autograd import grad

x1 = torch.tensor(2, requires_grad = True, dtype=torch.float16)
x2 = torch.tensor(3, requires_grad = True, dtype=torch.float16)
x3 = torch.tensor(1, requires_grad = True, dtype=torch.float16)
x4 = torch.tensor(4, requires_grad = True, dtype=torch.float16)

In [13]:
x1,x2,x3,x4

(tensor(2., dtype=torch.float16, requires_grad=True),
 tensor(3., dtype=torch.float16, requires_grad=True),
 tensor(1., dtype=torch.float16, requires_grad=True),
 tensor(4., dtype=torch.float16, requires_grad=True))

In [14]:
z1 = x1 * x2
z2 = x3 * x4

f = z1 + z2

In [15]:
z1,z2,f

(tensor(6., dtype=torch.float16, grad_fn=<MulBackward0>),
 tensor(4., dtype=torch.float16, grad_fn=<MulBackward0>),
 tensor(10., dtype=torch.float16, grad_fn=<AddBackward0>))

In [16]:
df_dx = grad(outputs=f, inputs=[x1, x2, x3, x4]) #what if you forget an element here?

print(f'gradient of x1 = {df_dx[0]}')
print(f'gradient of x2 = {df_dx[1]}')
print(f'gradient of x3 = {df_dx[2]}')
print(f'gradient of x4 = {df_dx[3]}')

gradient of x1 = 3.0
gradient of x2 = 2.0
gradient of x3 = 4.0
gradient of x4 = 1.0
