<a href="https://colab.research.google.com/github/pswami12/DataScienceFiles/blob/main/Class_3_AIDL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
V0 = torch.tensor(1.3)
V1 = torch.tensor([1.,2.,3.])
V2 = torch.tensor([[1.,2.],[4.,5.]])
print(f'{V0}, {V1}, {V2}')

1.2999999523162842, tensor([1., 2., 3.]), tensor([[1., 2.],
        [4., 5.]])


In [3]:
import numpy as np
V0 = np.array(1.3)
V1 = np.array([1.,2.,3.])
V2 = np.array([[1.,2.],[4.,5.]])
print(f'{V0}, {V1}, {V2}')

1.3, [1. 2. 3.], [[1. 2.]
 [4. 5.]]


In [4]:
numpy_array = np.array([1,2,3])
numpy_array

array([1, 2, 3])

In [5]:
numpy_array*4

array([ 4,  8, 12])

In [6]:
t1 = torch.Tensor(numpy_array)
t1
#Constructor - same as torch.FloatTensor
#Uses a default float32 tensor, can be changed
#all other tensor inherits from this main tensor class
#torch.tensor(data, dtype=None, device=None, requires_grad =False) -> Tensor

tensor([1., 2., 3.])

In [7]:
t2 = torch.tensor(numpy_array)
t2
#Factory function
#produces a new tensor with same type
#does not share underlying memory with numpy
#always copies the data
#torch.tensor(x) is equivalent to x.clone().detach()
#recommend to use

tensor([1, 2, 3])

In [8]:
t3 = torch.as_tensor(numpy_array)
t3
#produce a new tensor with same dtype
#share underlying memory with numpy, changing one will change other
#can accepts any array like python data structure
#always try to avoid copies of the data (like using numpy's stored values directly)
#Have to manually add required_grad_() function, or doesn't support requires_grad flag
#recommend to use

tensor([1, 2, 3])

In [9]:
t4 = torch.from_numpy(numpy_array)
t4
#Factory function
#produces a new tensor with same dtype
#can accept only numpy arrays
#share underlying memory with numpy, changing one will change other

tensor([1, 2, 3])

In [10]:
numpy_array*=4
t1,t2,t3,t4

(tensor([1., 2., 3.]),
 tensor([1, 2, 3]),
 tensor([ 4,  8, 12]),
 tensor([ 4,  8, 12]))

In [11]:
data = torch.tensor([[1,2,3],[4,5,6]])
data[1, 0], data[0, : 2]

(tensor(4), tensor([1, 2]))

In [12]:
from torch.autograd import grad

x1 = torch.tensor(2, requires_grad = True, dtype=torch.float16)
x2 = torch.tensor(3, requires_grad = True, dtype=torch.float16)
x3 = torch.tensor(1, requires_grad = True, dtype=torch.float16)
x4 = torch.tensor(4, requires_grad = True, dtype=torch.float16)

In [13]:
x1,x2,x3,x4

(tensor(2., dtype=torch.float16, requires_grad=True),
 tensor(3., dtype=torch.float16, requires_grad=True),
 tensor(1., dtype=torch.float16, requires_grad=True),
 tensor(4., dtype=torch.float16, requires_grad=True))

In [14]:
z1 = x1 * x2
z2 = x3 * x4

f = z1 + z2

In [15]:
z1,z2,f

(tensor(6., dtype=torch.float16, grad_fn=<MulBackward0>),
 tensor(4., dtype=torch.float16, grad_fn=<MulBackward0>),
 tensor(10., dtype=torch.float16, grad_fn=<AddBackward0>))

In [16]:
df_dx = grad(outputs=f, inputs=[x1, x2, x3, x4]) #what if you forget an element here?

print(f'gradient of x1 = {df_dx[0]}')
print(f'gradient of x2 = {df_dx[1]}')
print(f'gradient of x3 = {df_dx[2]}')
print(f'gradient of x4 = {df_dx[3]}')

gradient of x1 = 3.0
gradient of x2 = 2.0
gradient of x3 = 4.0
gradient of x4 = 1.0


In [17]:
t = torch.tensor([
    [0, 0, 0, 0],
    [1, 1, 1, 1],
    [2, 2, 2, 2]
], dtype=torch.float32)

In [18]:
# we have two ways to access the shape of tensors
t.shape, t.size()

(torch.Size([3, 4]), torch.Size([3, 4]))

In [19]:
# we can also learn about the total elements in a tensor by
torch.tensor(t.shape).prod()

tensor(12)

In [20]:
# or by using numel
t.numel()

12

In [21]:
t.reshape(1, 12)

tensor([[0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.]])

In [22]:
t.reshape(2, 6)

tensor([[0., 0., 0., 0., 1., 1.],
        [1., 1., 2., 2., 2., 2.]])

In [23]:
t.reshape(6, 2)

tensor([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.]])

In [24]:
t.reshape(3, 4)

tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.]])

In [25]:
t.reshape(4, 3)

tensor([[0., 0., 0.],
        [0., 1., 1.],
        [1., 1., 2.],
        [2., 2., 2.]])

In [26]:
#Change rank of a tensor
t.reshape(2, 2, 3)

tensor([[[0., 0., 0.],
         [0., 1., 1.]],

        [[1., 1., 2.],
         [2., 2., 2.]]])

In [27]:
#Squeezing a Tensor

#Removes all the dimensions that have a length of 1

#Unsqueezing a Tensor Adds a dimension that has a length of 1.

print(t.reshape(1, 12))
print(t.reshape(1, 12).shape)

tensor([[0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.]])
torch.Size([1, 12])


In [28]:
print(t.reshape(1, 12).squeeze())
print(t.reshape(1, 12).squeeze().shape)

tensor([0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.])
torch.Size([12])


In [29]:
print(t.reshape(1, 12).squeeze().unsqueeze(dim=0))
print(t.reshape(1, 12).squeeze().unsqueeze(dim=0).shape)

tensor([[0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.]])
torch.Size([1, 12])


#Use cases?

Neural networks are always trained in a batch of samples. This is troubling because when we want to test 1 image, we do not have an array, we only have 1 image. Well we unsqueeze it to fake a batch.

We use this function that is very common, called Flatten. This essentially create a new tensor that is only 1D. This is done to connect our data to next Fully Connected Layers. We use squeeze function for this.

Let's implement such a function.

In [30]:
def flatten(t):
  t = t.reshape(1, -1)
  # In PyTorch this forces PyTorch to figure out the next dimension automatically so numel remains constant.
  # i.e. if tensor was of 2x3x4 dimensions (1, -1) will calculate 24 for us and get us a 1x24 tensor. 
  t = t.squeeze()
  # now we need to squeeze it since it is still acting like a 2D array.
  return t

In [31]:
t.shape

torch.Size([3, 4])

In [32]:
flatten(t)

tensor([0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.])

In [33]:
#Tensor concatenation
t1 = torch.tensor([
    [1, 2],
    [3, 4]
])

t2 = torch.tensor([
    [5, 6],
    [7, 8]
])

torch.cat((t1, t2), dim=0), torch.cat((t1, t2), dim=1)

(tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]),
 tensor([[1, 2, 5, 6],
         [3, 4, 7, 8]]))

In [34]:
#More on Flatten and batches

img1 = torch.tensor([
  [1, 1, 1, 1],
  [1, 1, 1, 1],
  [1, 1, 1, 1],
  [1, 1, 1, 1]
])

img2 = torch.tensor([
  [2, 2, 2, 2],
  [2, 2, 2, 2],
  [2, 2, 2, 2],
  [2, 2, 2, 2]
])

img3 = torch.tensor([
  [3, 3, 3, 3],
  [3, 3, 3, 3],
  [3, 3, 3, 3],
  [3, 3, 3, 3]
])

Assume that above we have 3 4x4 black and white images.

But we feed batches to our neural networks. How do we convert this into a batch (one of the many ways)

In [35]:
batch = torch.stack((img1, img2, img3))
batch.shape

torch.Size([3, 4, 4])

In [36]:
batch

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

3 above represents our batch size, and 4x4 represents the shape of our images. But that is not how NN expects the data to be. It needs to be explicitly specified that we have 1 channel and that channel has 4x4 size data, so

In [37]:
batch = batch.reshape(3, 1, 4, 4)
batch

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [38]:
# let's get our first image

batch[0]

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [39]:
# let's get the first channel of our first image

batch[0][0]

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [40]:
# let's get the first row of our first channel of our first image

batch[0][0][0]

tensor([1, 1, 1, 1])

In [41]:
# let's get the first pixel of the first row of our first channel of our first image

batch[0][0][0][0]

tensor(1)

Let's see how we flatten our image inside the

1.List item
2. List item


In [42]:
batch.reshape(1, -1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [43]:
batch.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [44]:
batch.reshape(batch.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [45]:
batch.flatten() # inbuilt PyTorch method

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

*But* what if we wanted to flatten the images but not collapse them into a single dim? Above data is anyways useless for our DNN

In [46]:
batch.reshape(3, -1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [47]:
# or inbuilt method
batch.flatten(start_dim=1).shape

torch.Size([3, 16])

In [48]:
# or inbuilt method
batch.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [49]:
t1 = torch.tensor([
    [1, 2],
    [3, 4]
], dtype=torch.float32)

t2 = torch.tensor([
    [5, 6],
    [7, 8]
], dtype=torch.float32)

In [50]:
t1 + t2 

tensor([[ 6.,  8.],
        [10., 12.]])

In [51]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [52]:
print(t1.add(2))

print(t1.sub(2))

print(t1.mul(2))

print(t1.div(2))

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [53]:
t = torch.tensor([
    [0, 5, 7],
    [6, 0, 7],
    [0, 8, 0]
], dtype=torch.float32)

In [54]:
t.eq(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [55]:
t.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [56]:
t.sqrt()

tensor([[0.0000, 2.2361, 2.6458],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [57]:
t.neg()

tensor([[-0., -5., -7.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

**Reduction Functions**
A reduction operation on a tensor is an operation that reduces the number of elements contained within the tensor

In [58]:
t = torch.tensor([
    [0, 5, 7],
    [6, 0, 7],
    [0, 8, 0]
], dtype=torch.float32)

In [59]:
t.sum()

tensor(33.)

In [60]:
t.std()

tensor(3.5707)

Reduction operation do not recessarily reduce tensors to single value. We can perform operations on a specific axis as well

In [61]:
t = torch.tensor([
  [1, 1, 1, 1],
  [2, 2, 2, 2],
  [3, 3, 3, 3],
  [4, 4, 4, 4]
])

In [62]:
t.sum(dim=0) # 0th axis is arrays (y-axis here), 1st axis is numbers(x-axis here)

tensor([10, 10, 10, 10])

In [63]:
t.sum(dim=1)

tensor([ 4,  8, 12, 16])

In [64]:
#ArgMax and ArgMin
t.argmax(), t.max()

(tensor(12), tensor(4))

In [65]:
t.argmin(), t.min()

(tensor(0), tensor(1))

In [66]:
t = torch.tensor([
    [1, 0, 0, 2],
    [0, 3, 3, 0],
    [4, 0, 0, 5]
], dtype=torch.float32)

In [67]:
t.max(dim=0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [68]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))

In [69]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [70]:
t.argmax(dim=1)

tensor([3, 1, 3])

In [71]:
t.mean(), t.mean().item() #item works only with scalar value tensors

(tensor(1.5000), 1.5)

In [72]:
# how to get multiple values out of a tensor as item only works with scalar values

t.mean(dim=0).tolist(), t.mean(dim=0).tolist()[0]

([1.6666666269302368, 1.0, 1.0, 2.3333332538604736], 1.6666666269302368)

In [73]:
# or

t.mean(dim=0).numpy(), t.mean(dim=0).numpy()[0]

(array([1.6666666, 1.       , 1.       , 2.3333333], dtype=float32), 1.6666666)

## **Churn classification Pytorch**

In [74]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [75]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')

In [76]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [77]:
dataset.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)

In [78]:
dataset.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [79]:
dataset_new = pd.get_dummies(dataset, ['Geography', 'Gender'], drop_first=True)

In [80]:
X = dataset_new[dataset_new.columns.difference(['Exited'])]
y = dataset_new['Exited']

In [82]:
from sklearn.model_selection import train_test_split

In [83]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =123)

In [84]:
#Scaling variables - Helps to converge quickly

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [85]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import torch.nn.functional as F
import torch.utils.data
import torch.optim as optim

In [86]:
# Numpy to Tensor Conversion (Train Set)
X_train = torch.from_numpy(X_train)
y_train = torch.from_numpy(y_train.values).view(-1,1)

# Numpy to Tensor Conversion (Train Set)
X_test = torch.from_numpy(X_test)
y_test = torch.from_numpy(y_test.values).view(-1,1)

In [87]:
X_train

tensor([[ 1.5132,  0.0785, -0.0222,  ...,  0.9699, -0.9170, -1.3889],
        [ 1.7017, -1.2193,  0.4439,  ...,  0.9699,  0.7988,  1.3750],
        [-0.5600, -1.2193, -0.6644,  ...,  0.9699,  0.7988,  0.6840],
        ...,
        [-1.7851,  0.4509,  0.3610,  ..., -1.0311,  0.7988, -0.3525],
        [-0.8427,  0.2870, -0.0740,  ...,  0.9699, -0.9170, -0.0070],
        [-0.3715, -1.2193,  0.3714,  ..., -1.0311, -0.9170, -0.3525]],
       dtype=torch.float64)

In [88]:
y_train

tensor([[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]])

In [89]:
X_train.shape

torch.Size([7000, 11])

In [95]:
class ANN(nn.Module):
    def __init__(self, input_dim = 11, output_dim = 1): #no of features are 11 -> input_dim
        super(ANN, self).__init__()
        self.fc1 = nn.Linear(input_dim, 6) #Hidden Layer 1
        self.fc2 = nn.Linear(6, 6)         #Hidden Layer2
        self.output_layer = nn.Linear(6,output_dim) #Output Layer

    
    # Feed Forward Function
    def forward(self, x):
        x = F.relu(self.fc1(x))    # Add ReLU activation function to each layer
        x = F.relu(self.fc2(x))
        x = F.sigmoid(self.output_layer(x))
        return x     # Return the created model

In [96]:
# Hyper-parameters
input_size = 11
output_size = 1
num_epochs = 1000
learning_rate = 0.01

In [97]:
# Create the Neural Network Model
model = ANN(input_dim = input_size, output_dim = output_size)
# Print its architecture
print(model)

ANN(
  (fc1): Linear(in_features=11, out_features=6, bias=True)
  (fc2): Linear(in_features=6, out_features=6, bias=True)
  (output_layer): Linear(in_features=6, out_features=1, bias=True)
)


In [98]:
#Loss & Optimizer
criterion = nn.BCELoss()   # specify loss function - BCELoss: Binary Cross Entropy loss
#optimizer = optim.SGD(model.parameters(), lr=learning_rate) # specify optimizer
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

In [99]:
#Before model building, calculate the test loss for verfication
model.eval()     #not updating the model weights
data_test = Variable(X_test).float()
target_test = Variable(y_test).type(torch.FloatTensor)
y_pred_test = model(data_test)
before_train = criterion(y_pred_test, target_test) 
print('Test loss before training' , before_train.item())

Test loss before training 0.8494329452514648
