<a href="https://colab.research.google.com/github/pswami12/DataScienceFiles/blob/main/Class_3_AIDL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
V0 = torch.tensor(1.3)
V1 = torch.tensor([1.,2.,3.])
V2 = torch.tensor([[1.,2.],[4.,5.]])
print(f'{V0}, {V1}, {V2}')

1.2999999523162842, tensor([1., 2., 3.]), tensor([[1., 2.],
        [4., 5.]])


In [4]:
import numpy as np
V0 = np.array(1.3)
V1 = np.array([1.,2.,3.])
V2 = np.array([[1.,2.],[4.,5.]])
print(f'{V0}, {V1}, {V2}')

1.3, [1. 2. 3.], [[1. 2.]
 [4. 5.]]


In [5]:
numpy_array = np.array([1,2,3])
numpy_array

array([1, 2, 3])

In [6]:
t1 = torch.Tensor(numpy_array)
t1
#Constructor - same as torch.FloatTensor
#Uses a default float32 tensor, can be changed
#all other tensor inherits from this main tensor class
#torch.tensor(data, dtype=None, device=None, requires_grad =False) -> Tensor

tensor([1., 2., 3.])

In [7]:
t2 = torch.tensor(numpy_array)
t2
#Factory function
#produces a new tensor with same type
#does not share underlying memory with numpy
#always copies the data
#torch.tensor(x) is equivalent to x.clone().detach()
#recommend to use

tensor([1, 2, 3])

In [8]:
t3 = torch.as_tensor(numpy_array)
t3
#produce a new tensor with same dtype
#share underlying memory with numpy, changing one will change other
#can accepts any array like python data structure

tensor([1, 2, 3])

In [9]:
t4 = torch.from_numpy(numpy_array)
t4

tensor([1, 2, 3])