<a href="https://colab.research.google.com/github/pswami12/DataScienceFiles/blob/main/Class_3_AIDL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
V0 = torch.tensor(1.3)
V1 = torch.tensor([1.,2.,3.])
V2 = torch.tensor([[1.,2.],[4.,5.]])
print(f'{V0}, {V1}, {V2}')

1.2999999523162842, tensor([1., 2., 3.]), tensor([[1., 2.],
        [4., 5.]])


In [3]:
import numpy as np
V0 = np.array(1.3)
V1 = np.array([1.,2.,3.])
V2 = np.array([[1.,2.],[4.,5.]])
print(f'{V0}, {V1}, {V2}')

1.3, [1. 2. 3.], [[1. 2.]
 [4. 5.]]


In [4]:
numpy_array = np.array([1,2,3])
numpy_array

array([1, 2, 3])

In [5]:
numpy_array*4

array([ 4,  8, 12])

In [6]:
t1 = torch.Tensor(numpy_array)
t1
#Constructor - same as torch.FloatTensor
#Uses a default float32 tensor, can be changed
#all other tensor inherits from this main tensor class
#torch.tensor(data, dtype=None, device=None, requires_grad =False) -> Tensor

tensor([1., 2., 3.])

In [7]:
t2 = torch.tensor(numpy_array)
t2
#Factory function
#produces a new tensor with same type
#does not share underlying memory with numpy
#always copies the data
#torch.tensor(x) is equivalent to x.clone().detach()
#recommend to use

tensor([1, 2, 3])

In [8]:
t3 = torch.as_tensor(numpy_array)
t3
#produce a new tensor with same dtype
#share underlying memory with numpy, changing one will change other
#can accepts any array like python data structure
#always try to avoid copies of the data (like using numpy's stored values directly)
#Have to manually add required_grad_() function, or doesn't support requires_grad flag
#recommend to use

tensor([1, 2, 3])

In [9]:
t4 = torch.from_numpy(numpy_array)
t4
#Factory function
#produces a new tensor with same dtype
#can accept only numpy arrays
#share underlying memory with numpy, changing one will change other

tensor([1, 2, 3])

In [10]:
numpy_array*=4
t1,t2,t3,t4

(tensor([1., 2., 3.]),
 tensor([1, 2, 3]),
 tensor([ 4,  8, 12]),
 tensor([ 4,  8, 12]))

In [11]:
data = torch.tensor([[1,2,3],[4,5,6]])
data[1, 0], data[0, : 2]

(tensor(4), tensor([1, 2]))

In [12]:
from torch.autograd import grad

x1 = torch.tensor(2, requires_grad = True, dtype=torch.float16)
x2 = torch.tensor(3, requires_grad = True, dtype=torch.float16)
x3 = torch.tensor(1, requires_grad = True, dtype=torch.float16)
x4 = torch.tensor(4, requires_grad = True, dtype=torch.float16)

In [13]:
x1,x2,x3,x4

(tensor(2., dtype=torch.float16, requires_grad=True),
 tensor(3., dtype=torch.float16, requires_grad=True),
 tensor(1., dtype=torch.float16, requires_grad=True),
 tensor(4., dtype=torch.float16, requires_grad=True))

In [14]:
z1 = x1 * x2
z2 = x3 * x4

f = z1 + z2

In [15]:
z1,z2,f

(tensor(6., dtype=torch.float16, grad_fn=<MulBackward0>),
 tensor(4., dtype=torch.float16, grad_fn=<MulBackward0>),
 tensor(10., dtype=torch.float16, grad_fn=<AddBackward0>))

In [16]:
df_dx = grad(outputs=f, inputs=[x1, x2, x3, x4]) #what if you forget an element here?

print(f'gradient of x1 = {df_dx[0]}')
print(f'gradient of x2 = {df_dx[1]}')
print(f'gradient of x3 = {df_dx[2]}')
print(f'gradient of x4 = {df_dx[3]}')

gradient of x1 = 3.0
gradient of x2 = 2.0
gradient of x3 = 4.0
gradient of x4 = 1.0


In [17]:
t = torch.tensor([
    [0, 0, 0, 0],
    [1, 1, 1, 1],
    [2, 2, 2, 2]
], dtype=torch.float32)

In [20]:
# we have two ways to access the shape of tensors
t.shape, t.size()

(torch.Size([3, 4]), torch.Size([3, 4]))

In [21]:
# we can also learn about the total elements in a tensor by
torch.tensor(t.shape).prod()

tensor(12)

In [22]:
# or by using numel
t.numel()

12

In [23]:
t.reshape(1, 12)

tensor([[0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.]])

In [24]:
t.reshape(2, 6)

tensor([[0., 0., 0., 0., 1., 1.],
        [1., 1., 2., 2., 2., 2.]])

In [25]:
t.reshape(6, 2)

tensor([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.]])

In [26]:
t.reshape(3, 4)

tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.]])

In [27]:
t.reshape(4, 3)

tensor([[0., 0., 0.],
        [0., 1., 1.],
        [1., 1., 2.],
        [2., 2., 2.]])

In [28]:
#Change rank of a tensor
t.reshape(2, 2, 3)

tensor([[[0., 0., 0.],
         [0., 1., 1.]],

        [[1., 1., 2.],
         [2., 2., 2.]]])

In [29]:
#Squeezing a Tensor

#Removes all the dimensions that have a length of 1

#Unsqueezing a Tensor Adds a dimension that has a length of 1.

print(t.reshape(1, 12))
print(t.reshape(1, 12).shape)

tensor([[0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.]])
torch.Size([1, 12])


In [30]:
print(t.reshape(1, 12).squeeze())
print(t.reshape(1, 12).squeeze().shape)

tensor([0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.])
torch.Size([12])


In [31]:
print(t.reshape(1, 12).squeeze().unsqueeze(dim=0))
print(t.reshape(1, 12).squeeze().unsqueeze(dim=0).shape)

tensor([[0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.]])
torch.Size([1, 12])


#Use cases?

Neural networks are always trained in a batch of samples. This is troubling because when we want to test 1 image, we do not have an array, we only have 1 image. Well we unsqueeze it to fake a batch.

We use this function that is very common, called Flatten. This essentially create a new tensor that is only 1D. This is done to connect our data to next Fully Connected Layers. We use squeeze function for this.

Let's implement such a function.

In [32]:
def flatten(t):
  t = t.reshape(1, -1)
  # In PyTorch this forces PyTorch to figure out the next dimension automatically so numel remains constant.
  # i.e. if tensor was of 2x3x4 dimensions (1, -1) will calculate 24 for us and get us a 1x24 tensor. 
  t = t.squeeze()
  # now we need to squeeze it since it is still acting like a 2D array.
  return t

In [33]:
t.shape

torch.Size([3, 4])

In [34]:
flatten(t)

tensor([0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.])

In [35]:
#Tensor concatenation
t1 = torch.tensor([
    [1, 2],
    [3, 4]
])

t2 = torch.tensor([
    [5, 6],
    [7, 8]
])

torch.cat((t1, t2), dim=0), torch.cat((t1, t2), dim=1)

(tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]),
 tensor([[1, 2, 5, 6],
         [3, 4, 7, 8]]))

In [36]:
#More on Flatten and batches

img1 = torch.tensor([
  [1, 1, 1, 1],
  [1, 1, 1, 1],
  [1, 1, 1, 1],
  [1, 1, 1, 1]
])

img2 = torch.tensor([
  [2, 2, 2, 2],
  [2, 2, 2, 2],
  [2, 2, 2, 2],
  [2, 2, 2, 2]
])

img3 = torch.tensor([
  [3, 3, 3, 3],
  [3, 3, 3, 3],
  [3, 3, 3, 3],
  [3, 3, 3, 3]
])

Assume that above we have 3 4x4 black and white images.

But we feed batches to our neural networks. How do we convert this into a batch (one of the many ways)

In [37]:
batch = torch.stack((img1, img2, img3))
batch.shape

torch.Size([3, 4, 4])

In [38]:
batch

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

3 above represents our batch size, and 4x4 represents the shape of our images. But that is not how NN expects the data to be. It needs to be explicitly specified that we have 1 channel and that channel has 4x4 size data, so

In [39]:
batch = batch.reshape(3, 1, 4, 4)
batch

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [40]:
# let's get our first image

batch[0]

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [41]:
# let's get the first channel of our first image

batch[0][0]

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [42]:
# let's get the first row of our first channel of our first image

batch[0][0][0]

tensor([1, 1, 1, 1])

In [43]:
# let's get the first pixel of the first row of our first channel of our first image

batch[0][0][0][0]

tensor(1)

Let's see how we flatten our image inside the

1.List item
2. List item


In [44]:
batch.reshape(1, -1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [45]:
batch.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [46]:
batch.reshape(batch.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [47]:
batch.flatten() # inbuilt PyTorch method

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

*But* what if we wanted to flatten the images but not collapse them into a single dim? Above data is anyways useless for our DNN

In [48]:
batch.reshape(3, -1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [49]:
# or inbuilt method
batch.flatten(start_dim=1).shape

torch.Size([3, 16])

In [50]:
# or inbuilt method
batch.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [51]:
t1 = torch.tensor([
    [1, 2],
    [3, 4]
], dtype=torch.float32)

t2 = torch.tensor([
    [5, 6],
    [7, 8]
], dtype=torch.float32)

In [52]:
t1 + t2 

tensor([[ 6.,  8.],
        [10., 12.]])

In [53]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [54]:
print(t1.add(2))

print(t1.sub(2))

print(t1.mul(2))

print(t1.div(2))

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [55]:
t = torch.tensor([
    [0, 5, 7],
    [6, 0, 7],
    [0, 8, 0]
], dtype=torch.float32)

In [56]:
t.eq(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [57]:
t.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [58]:
t.sqrt()

tensor([[0.0000, 2.2361, 2.6458],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [59]:
t.neg()

tensor([[-0., -5., -7.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

**Reduction Functions**
A reduction operation on a tensor is an operation that reduces the number of elements contained within the tensor

In [60]:
t = torch.tensor([
    [0, 5, 7],
    [6, 0, 7],
    [0, 8, 0]
], dtype=torch.float32)

In [61]:
t.sum()

tensor(33.)

In [62]:
t.std()

tensor(3.5707)

Reduction operation do not recessarily reduce tensors to single value. We can perform operations on a specific axis as well

In [63]:
t = torch.tensor([
  [1, 1, 1, 1],
  [2, 2, 2, 2],
  [3, 3, 3, 3],
  [4, 4, 4, 4]
])

In [64]:
t.sum(dim=0) # 0th axis is arrays (y-axis here), 1st axis is numbers(x-axis here)

tensor([10, 10, 10, 10])

In [65]:
t.sum(dim=1)

tensor([ 4,  8, 12, 16])

In [66]:
#ArgMax and ArgMin
t.argmax(), t.max()

(tensor(12), tensor(4))

In [67]:
t.argmin(), t.min()

(tensor(0), tensor(1))

In [68]:
t = torch.tensor([
    [1, 0, 0, 2],
    [0, 3, 3, 0],
    [4, 0, 0, 5]
], dtype=torch.float32)

In [69]:
t.max(dim=0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [70]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))

In [71]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [72]:
t.argmax(dim=1)

tensor([3, 1, 3])

In [73]:
t.mean(), t.mean().item() #item works only with scalar value tensors

(tensor(1.5000), 1.5)

In [74]:
# how to get multiple values out of a tensor as item only works with scalar values

t.mean(dim=0).tolist(), t.mean(dim=0).tolist()[0]

([1.6666666269302368, 1.0, 1.0, 2.3333332538604736], 1.6666666269302368)

In [75]:
# or

t.mean(dim=0).numpy(), t.mean(dim=0).numpy()[0]

(array([1.6666666, 1.       , 1.       , 2.3333333], dtype=float32), 1.6666666)