<a href="https://colab.research.google.com/github/pswami12/DataScienceFiles/blob/main/Class_3_AIDL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch

In [2]:
V0 = torch.tensor(1.3)
V1 = torch.tensor([1.,2.,3.])
V2 = torch.tensor([[1.,2.],[4.,5.]])
print(f'{V0}, {V1}, {V2}')

1.2999999523162842, tensor([1., 2., 3.]), tensor([[1., 2.],
        [4., 5.]])


In [3]:
import numpy as np
V0 = np.array(1.3)
V1 = np.array([1.,2.,3.])
V2 = np.array([[1.,2.],[4.,5.]])
print(f'{V0}, {V1}, {V2}')

1.3, [1. 2. 3.], [[1. 2.]
 [4. 5.]]


In [4]:
numpy_array = np.array([1,2,3])
numpy_array

array([1, 2, 3])

In [5]:
numpy_array*4

array([ 4,  8, 12])

In [6]:
t1 = torch.Tensor(numpy_array)
t1
#Constructor - same as torch.FloatTensor
#Uses a default float32 tensor, can be changed
#all other tensor inherits from this main tensor class
#torch.tensor(data, dtype=None, device=None, requires_grad =False) -> Tensor

tensor([1., 2., 3.])

In [7]:
t2 = torch.tensor(numpy_array)
t2
#Factory function
#produces a new tensor with same type
#does not share underlying memory with numpy
#always copies the data
#torch.tensor(x) is equivalent to x.clone().detach()
#recommend to use

tensor([1, 2, 3])

In [8]:
t3 = torch.as_tensor(numpy_array)
t3
#produce a new tensor with same dtype
#share underlying memory with numpy, changing one will change other
#can accepts any array like python data structure
#always try to avoid copies of the data (like using numpy's stored values directly)
#Have to manually add required_grad_() function, or doesn't support requires_grad flag
#recommend to use

tensor([1, 2, 3])

In [9]:
t4 = torch.from_numpy(numpy_array)
t4
#Factory function
#produces a new tensor with same dtype
#can accept only numpy arrays
#share underlying memory with numpy, changing one will change other

tensor([1, 2, 3])

In [10]:
numpy_array*=4
t1,t2,t3,t4

(tensor([1., 2., 3.]),
 tensor([1, 2, 3]),
 tensor([ 4,  8, 12]),
 tensor([ 4,  8, 12]))

In [11]:
data = torch.tensor([[1,2,3],[4,5,6]])
data[1, 0], data[0, : 2]

(tensor(4), tensor([1, 2]))

In [12]:
from torch.autograd import grad

x1 = torch.tensor(2, requires_grad = True, dtype=torch.float16)
x2 = torch.tensor(3, requires_grad = True, dtype=torch.float16)
x3 = torch.tensor(1, requires_grad = True, dtype=torch.float16)
x4 = torch.tensor(4, requires_grad = True, dtype=torch.float16)

In [13]:
x1,x2,x3,x4

(tensor(2., dtype=torch.float16, requires_grad=True),
 tensor(3., dtype=torch.float16, requires_grad=True),
 tensor(1., dtype=torch.float16, requires_grad=True),
 tensor(4., dtype=torch.float16, requires_grad=True))

In [14]:
z1 = x1 * x2
z2 = x3 * x4

f = z1 + z2

In [15]:
z1,z2,f

(tensor(6., dtype=torch.float16, grad_fn=<MulBackward0>),
 tensor(4., dtype=torch.float16, grad_fn=<MulBackward0>),
 tensor(10., dtype=torch.float16, grad_fn=<AddBackward0>))

In [16]:
df_dx = grad(outputs=f, inputs=[x1, x2, x3, x4]) #what if you forget an element here?

print(f'gradient of x1 = {df_dx[0]}')
print(f'gradient of x2 = {df_dx[1]}')
print(f'gradient of x3 = {df_dx[2]}')
print(f'gradient of x4 = {df_dx[3]}')

gradient of x1 = 3.0
gradient of x2 = 2.0
gradient of x3 = 4.0
gradient of x4 = 1.0


In [17]:
t = torch.tensor([
    [0, 0, 0, 0],
    [1, 1, 1, 1],
    [2, 2, 2, 2]
], dtype=torch.float32)

In [18]:
# we have two ways to access the shape of tensors
t.shape, t.size()

(torch.Size([3, 4]), torch.Size([3, 4]))

In [19]:
# we can also learn about the total elements in a tensor by
torch.tensor(t.shape).prod()

tensor(12)

In [20]:
# or by using numel
t.numel()

12

In [21]:
t.reshape(1, 12)

tensor([[0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.]])

In [22]:
t.reshape(2, 6)

tensor([[0., 0., 0., 0., 1., 1.],
        [1., 1., 2., 2., 2., 2.]])

In [23]:
t.reshape(6, 2)

tensor([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.]])

In [24]:
t.reshape(3, 4)

tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.]])

In [25]:
t.reshape(4, 3)

tensor([[0., 0., 0.],
        [0., 1., 1.],
        [1., 1., 2.],
        [2., 2., 2.]])

In [26]:
#Change rank of a tensor
t.reshape(2, 2, 3)

tensor([[[0., 0., 0.],
         [0., 1., 1.]],

        [[1., 1., 2.],
         [2., 2., 2.]]])

In [27]:
#Squeezing a Tensor

#Removes all the dimensions that have a length of 1

#Unsqueezing a Tensor Adds a dimension that has a length of 1.

print(t.reshape(1, 12))
print(t.reshape(1, 12).shape)

tensor([[0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.]])
torch.Size([1, 12])


In [28]:
print(t.reshape(1, 12).squeeze())
print(t.reshape(1, 12).squeeze().shape)

tensor([0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.])
torch.Size([12])


In [29]:
print(t.reshape(1, 12).squeeze().unsqueeze(dim=0))
print(t.reshape(1, 12).squeeze().unsqueeze(dim=0).shape)

tensor([[0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.]])
torch.Size([1, 12])


#Use cases?

Neural networks are always trained in a batch of samples. This is troubling because when we want to test 1 image, we do not have an array, we only have 1 image. Well we unsqueeze it to fake a batch.

We use this function that is very common, called Flatten. This essentially create a new tensor that is only 1D. This is done to connect our data to next Fully Connected Layers. We use squeeze function for this.

Let's implement such a function.

In [30]:
def flatten(t):
  t = t.reshape(1, -1)
  # In PyTorch this forces PyTorch to figure out the next dimension automatically so numel remains constant.
  # i.e. if tensor was of 2x3x4 dimensions (1, -1) will calculate 24 for us and get us a 1x24 tensor.
  t = t.squeeze()
  # now we need to squeeze it since it is still acting like a 2D array.
  return t

In [31]:
t.shape

torch.Size([3, 4])

In [32]:
flatten(t)

tensor([0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.])

In [33]:
#Tensor concatenation
t1 = torch.tensor([
    [1, 2],
    [3, 4]
])

t2 = torch.tensor([
    [5, 6],
    [7, 8]
])

torch.cat((t1, t2), dim=0), torch.cat((t1, t2), dim=1)

(tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]),
 tensor([[1, 2, 5, 6],
         [3, 4, 7, 8]]))

In [34]:
#More on Flatten and batches

img1 = torch.tensor([
  [1, 1, 1, 1],
  [1, 1, 1, 1],
  [1, 1, 1, 1],
  [1, 1, 1, 1]
])

img2 = torch.tensor([
  [2, 2, 2, 2],
  [2, 2, 2, 2],
  [2, 2, 2, 2],
  [2, 2, 2, 2]
])

img3 = torch.tensor([
  [3, 3, 3, 3],
  [3, 3, 3, 3],
  [3, 3, 3, 3],
  [3, 3, 3, 3]
])

Assume that above we have 3 4x4 black and white images.

But we feed batches to our neural networks. How do we convert this into a batch (one of the many ways)

In [35]:
batch = torch.stack((img1, img2, img3))
batch.shape

torch.Size([3, 4, 4])

In [36]:
batch

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

3 above represents our batch size, and 4x4 represents the shape of our images. But that is not how NN expects the data to be. It needs to be explicitly specified that we have 1 channel and that channel has 4x4 size data, so

In [37]:
batch = batch.reshape(3, 1, 4, 4)
batch

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [38]:
# let's get our first image

batch[0]

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [39]:
# let's get the first channel of our first image

batch[0][0]

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [40]:
# let's get the first row of our first channel of our first image

batch[0][0][0]

tensor([1, 1, 1, 1])

In [41]:
# let's get the first pixel of the first row of our first channel of our first image

batch[0][0][0][0]

tensor(1)

Let's see how we flatten our image inside the

1.List item
2. List item


In [42]:
batch.reshape(1, -1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [43]:
batch.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [44]:
batch.reshape(batch.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [45]:
batch.flatten() # inbuilt PyTorch method

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

*But* what if we wanted to flatten the images but not collapse them into a single dim? Above data is anyways useless for our DNN

In [46]:
batch.reshape(3, -1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [47]:
# or inbuilt method
batch.flatten(start_dim=1).shape

torch.Size([3, 16])

In [48]:
# or inbuilt method
batch.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [49]:
t1 = torch.tensor([
    [1, 2],
    [3, 4]
], dtype=torch.float32)

t2 = torch.tensor([
    [5, 6],
    [7, 8]
], dtype=torch.float32)

In [50]:
t1 + t2

tensor([[ 6.,  8.],
        [10., 12.]])

In [51]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [52]:
print(t1.add(2))

print(t1.sub(2))

print(t1.mul(2))

print(t1.div(2))

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [53]:
t = torch.tensor([
    [0, 5, 7],
    [6, 0, 7],
    [0, 8, 0]
], dtype=torch.float32)

In [54]:
t.eq(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [55]:
t.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [56]:
t.sqrt()

tensor([[0.0000, 2.2361, 2.6458],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [57]:
t.neg()

tensor([[-0., -5., -7.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

**Reduction Functions**
A reduction operation on a tensor is an operation that reduces the number of elements contained within the tensor

In [58]:
t = torch.tensor([
    [0, 5, 7],
    [6, 0, 7],
    [0, 8, 0]
], dtype=torch.float32)

In [59]:
t.sum()

tensor(33.)

In [60]:
t.std()

tensor(3.5707)

Reduction operation do not recessarily reduce tensors to single value. We can perform operations on a specific axis as well

In [61]:
t = torch.tensor([
  [1, 1, 1, 1],
  [2, 2, 2, 2],
  [3, 3, 3, 3],
  [4, 4, 4, 4]
])

In [62]:
t.sum(dim=0) # 0th axis is arrays (y-axis here), 1st axis is numbers(x-axis here)

tensor([10, 10, 10, 10])

In [63]:
t.sum(dim=1)

tensor([ 4,  8, 12, 16])

In [64]:
#ArgMax and ArgMin
t.argmax(), t.max()

(tensor(12), tensor(4))

In [65]:
t.argmin(), t.min()

(tensor(0), tensor(1))

In [66]:
t = torch.tensor([
    [1, 0, 0, 2],
    [0, 3, 3, 0],
    [4, 0, 0, 5]
], dtype=torch.float32)

In [67]:
t.max(dim=0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [68]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))

In [69]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [70]:
t.argmax(dim=1)

tensor([3, 1, 3])

In [71]:
t.mean(), t.mean().item() #item works only with scalar value tensors

(tensor(1.5000), 1.5)

In [72]:
# how to get multiple values out of a tensor as item only works with scalar values

t.mean(dim=0).tolist(), t.mean(dim=0).tolist()[0]

([1.6666666269302368, 1.0, 1.0, 2.3333332538604736], 1.6666666269302368)

In [73]:
# or

t.mean(dim=0).numpy(), t.mean(dim=0).numpy()[0]

(array([1.6666666, 1.       , 1.       , 2.3333333], dtype=float32), 1.6666666)

## **Churn classification Pytorch**

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')

In [5]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
dataset.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)

In [7]:
dataset.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [8]:
dataset_new = pd.get_dummies(dataset, ['Geography', 'Gender'], drop_first=True)

In [9]:
X = dataset_new[dataset_new.columns.difference(['Exited'])]
y = dataset_new['Exited']

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =123)

In [12]:
#Scaling variables - Helps to converge quickly

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import torch.nn.functional as F
import torch.utils.data
import torch.optim as optim

In [14]:
# Numpy to Tensor Conversion (Train Set)
X_train = torch.from_numpy(X_train)
y_train = torch.from_numpy(y_train.values).view(-1,1)

# Numpy to Tensor Conversion (Train Set)
X_test = torch.from_numpy(X_test)
y_test = torch.from_numpy(y_test.values).view(-1,1)

In [15]:
X_train

tensor([[ 1.5132,  0.0785, -0.0222,  ...,  0.9699, -0.9170, -1.3889],
        [ 1.7017, -1.2193,  0.4439,  ...,  0.9699,  0.7988,  1.3750],
        [-0.5600, -1.2193, -0.6644,  ...,  0.9699,  0.7988,  0.6840],
        ...,
        [-1.7851,  0.4509,  0.3610,  ..., -1.0311,  0.7988, -0.3525],
        [-0.8427,  0.2870, -0.0740,  ...,  0.9699, -0.9170, -0.0070],
        [-0.3715, -1.2193,  0.3714,  ..., -1.0311, -0.9170, -0.3525]],
       dtype=torch.float64)

In [16]:
y_train

tensor([[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]])

In [17]:
X_train.shape

torch.Size([7000, 11])

In [18]:
class ANN(nn.Module):
    def __init__(self, input_dim = 11, output_dim = 1): #no of features are 11 -> input_dim
        super(ANN, self).__init__()
        self.fc1 = nn.Linear(input_dim, 6) #Hidden Layer 1
        self.fc2 = nn.Linear(6, 6)         #Hidden Layer2
        self.output_layer = nn.Linear(6,output_dim) #Output Layer


    # Feed Forward Function
    def forward(self, x):
        x = F.relu(self.fc1(x))    # Add ReLU activation function to each layer
        x = F.relu(self.fc2(x))
        x = F.sigmoid(self.output_layer(x))
        return x     # Return the created model

In [19]:
# Hyper-parameters
input_size = 11
output_size = 1
num_epochs = 1000
learning_rate = 0.01

In [20]:
# Create the Neural Network Model
model = ANN(input_dim = input_size, output_dim = output_size)
# Print its architecture
print(model)

ANN(
  (fc1): Linear(in_features=11, out_features=6, bias=True)
  (fc2): Linear(in_features=6, out_features=6, bias=True)
  (output_layer): Linear(in_features=6, out_features=1, bias=True)
)


In [21]:
#Loss & Optimizer
criterion = nn.BCELoss()   # specify loss function - BCELoss: Binary Cross Entropy loss
#optimizer = optim.SGD(model.parameters(), lr=learning_rate) # specify optimizer
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

In [22]:
#Before model building, calculate the test loss for verfication
model.eval()     #not updating the model weights
data_test = Variable(X_test).float()
target_test = Variable(y_test).type(torch.FloatTensor)
y_pred_test = model(data_test)
before_train = criterion(y_pred_test, target_test)
print('Test loss before training' , before_train.item())

Test loss before training 0.5970153212547302


In [23]:
# Train the model
model.train()
for epoch in range(num_epochs):
    data = Variable(X_train).float()
    target = Variable(y_train).type(torch.FloatTensor)

    # Forward pass
    outputs = model(data)
    loss = criterion(outputs, target)

    # Backward and optimize
    optimizer.zero_grad()   #sets the gradients to zero before we start backpropagation. This is a necessary step as PyTorch accumulates the gradients from the backward passes from the previous epochs.
    loss.backward() #we perform backward pass to computes the gradients.
    optimizer.step() #updates the weights accordingly.

    if (epoch+1) % 10 == 0:
        print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

Epoch [10/1000], Loss: 0.5429
Epoch [20/1000], Loss: 0.4732
Epoch [30/1000], Loss: 0.4426
Epoch [40/1000], Loss: 0.4182
Epoch [50/1000], Loss: 0.3978
Epoch [60/1000], Loss: 0.3774
Epoch [70/1000], Loss: 0.3619
Epoch [80/1000], Loss: 0.3526
Epoch [90/1000], Loss: 0.3483
Epoch [100/1000], Loss: 0.3457
Epoch [110/1000], Loss: 0.3439
Epoch [120/1000], Loss: 0.3424
Epoch [130/1000], Loss: 0.3411
Epoch [140/1000], Loss: 0.3402
Epoch [150/1000], Loss: 0.3395
Epoch [160/1000], Loss: 0.3391
Epoch [170/1000], Loss: 0.3386
Epoch [180/1000], Loss: 0.3383
Epoch [190/1000], Loss: 0.3379
Epoch [200/1000], Loss: 0.3376
Epoch [210/1000], Loss: 0.3372
Epoch [220/1000], Loss: 0.3369
Epoch [230/1000], Loss: 0.3366
Epoch [240/1000], Loss: 0.3363
Epoch [250/1000], Loss: 0.3361
Epoch [260/1000], Loss: 0.3358
Epoch [270/1000], Loss: 0.3355
Epoch [280/1000], Loss: 0.3352
Epoch [290/1000], Loss: 0.3350
Epoch [300/1000], Loss: 0.3347
Epoch [310/1000], Loss: 0.3345
Epoch [320/1000], Loss: 0.3343
Epoch [330/1000],

In [24]:
model.eval()              #not updating the model weights
data = Variable(X_train).float()
target = Variable(y_train).type(torch.FloatTensor)
y_pred = model(data)

In [25]:
y_pred

tensor([[0.1329],
        [0.0672],
        [0.0132],
        ...,
        [0.0029],
        [0.0416],
        [0.2513]], grad_fn=<SigmoidBackward0>)

In [26]:
#Accuarcy Metrics
import sklearn.metrics as metrics
from sklearn.metrics import confusion_matrix

metrics.roc_auc_score(y_train, y_pred.squeeze().detach().numpy())

0.8671004603319847

In [27]:
y_train.squeeze().detach().numpy()

array([0, 0, 0, ..., 0, 0, 0])

In [28]:
import numpy as np
np.mean(y_train.squeeze().detach().numpy())

0.20457142857142857

In [29]:
y_pred_cat = (y_pred.squeeze().detach().numpy() > 0.2)
y_pred_cat

array([False, False, False, ..., False, False,  True])

In [30]:
cm = confusion_matrix(y_train, y_pred_cat)
print(cm)

[[4434 1134]
 [ 341 1091]]


In [31]:
print(metrics.classification_report(y_train, y_pred_cat))

              precision    recall  f1-score   support

           0       0.93      0.80      0.86      5568
           1       0.49      0.76      0.60      1432

    accuracy                           0.79      7000
   macro avg       0.71      0.78      0.73      7000
weighted avg       0.84      0.79      0.80      7000



In [32]:
model.eval()     #not updating the model weights
data_test = Variable(X_test).float()
target_test = Variable(y_test).type(torch.FloatTensor)
y_pred_test = model(data_test)
after_train = criterion(y_pred_test, target_test)
print('Test loss after Training' , after_train.item())

Test loss after Training 0.3329657316207886


In [33]:
metrics.roc_auc_score(y_test, y_pred_test.squeeze().detach().numpy())

0.8625000431339396

In [34]:
y_pred_test_cat = (y_pred_test.squeeze().detach().numpy() > 0.2)

cm = confusion_matrix(y_test, y_pred_test_cat)
print(cm)
print(metrics.classification_report(y_test, y_pred_test_cat))

[[1912  483]
 [ 141  464]]
              precision    recall  f1-score   support

           0       0.93      0.80      0.86      2395
           1       0.49      0.77      0.60       605

    accuracy                           0.79      3000
   macro avg       0.71      0.78      0.73      3000
weighted avg       0.84      0.79      0.81      3000



# **Tensorflow with Keras _Basics**

In [35]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import sklearn
import tensorflow as tf

In [36]:
!nvidia-smi

Thu Jun 22 08:30:33 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [37]:
print(tf.__version__)

2.12.0


In [38]:
print(sklearn.__version__)

1.2.2


## **Tensors & Tensor Ops**

### **Constant**

In [39]:
t = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [40]:
t.dtype

tf.float32

In [41]:
t.shape

TensorShape([2, 3])

### **Variables**

In [42]:
t = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
t

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [43]:
t.dtype, t.shape

(tf.float32, TensorShape([2, 3]))

In [44]:
t.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [45]:
t[0,0].assign(99)
t

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[99.,  2.,  3.],
       [ 4.,  5.,  6.]], dtype=float32)>

In [46]:
t[1].assign([10, 20, 30])
t

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[99.,  2.,  3.],
       [10., 20., 30.]], dtype=float32)>

In [47]:
t[1] = [10, 20, 30]

TypeError: ignored

In [48]:
t.scatter_nd_update(indices=[[0, 0], [1, 1]],
                    updates=[33., 44.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[33.,  2.,  3.],
       [10., 44., 30.]], dtype=float32)>

### **Indexing**

In [49]:
t[1:, :]

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[10., 44., 30.]], dtype=float32)>

In [50]:
t[1:, ...]

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[10., 44., 30.]], dtype=float32)>

In [51]:
t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 2.,  3.],
       [44., 30.]], dtype=float32)>

In [52]:
t[..., 1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 2.,  3.],
       [44., 30.]], dtype=float32)>

### **Basic Ops**

In [53]:
t = t + 10
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[43., 12., 13.],
       [20., 54., 40.]], dtype=float32)>

In [54]:
t = t + tf.Variable([[1, 2, 3]], dtype='float32')
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[44., 14., 16.],
       [21., 56., 43.]], dtype=float32)>

In [55]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1936.,  196.,  256.],
       [ 441., 3136., 1849.]], dtype=float32)>

In [56]:
np.square(t)

array([[1936.,  196.,  256.],
       [ 441., 3136., 1849.]], dtype=float32)

In [57]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2388., 2396.],
       [2396., 5426.]], dtype=float32)>

In [58]:
from keras import backend as k

In [59]:
k.backend()

'tensorflow'

In [60]:
k.epsilon()

1e-07

In [61]:
k.image_data_format()

'channels_last'

In [62]:
data = k.placeholder(shape = (1,3,3))

In [63]:
data

<KerasTensor: shape=(1, 3, 3) dtype=float32 (created by layer 'input_1')>

In [64]:
a = k.placeholder(shape = (4,2))
b = k.placeholder(shape = (2,3))
c = k.dot(a,b)
c

<KerasTensor: shape=(4, 3) dtype=float32 (created by layer 'tf.linalg.matmul')>

In [65]:
res = k.ones(shape = (2,2))

In [66]:
k.eval(res)

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [67]:
a = k.random_uniform_variable(shape = (2, 3), low=0, high = 1)
b = k. random_uniform_variable(shape = (3,2), low = 0, high = 1)
c = k.dot(a, b)
k.int_shape(c)

(2, 2)

In [68]:
data

<KerasTensor: shape=(1, 3, 3) dtype=float32 (created by layer 'input_1')>

In [69]:
from keras.utils import to_categorical

In [70]:
labels = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [71]:
to_categorical(labels)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [72]:
from keras.utils import normalize
normalize([1, 2, 3, 4, 5])

array([[0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986]])

# **Churn_Classification_Keras**

In [73]:
import numpy as np
import pandas as pd
from tensorflow import keras
import matplotlib.pyplot as plt

In [74]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')

In [75]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [76]:
dataset.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)

In [77]:
dataset.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [78]:
dataset_new = pd.get_dummies(dataset, ['Geography', 'Gender'], drop_first=True)

In [80]:
dataset_new.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0               1        101348.88       1                  0   
1               1        112542.58       0                  0   
2               0        113931.57       1                  0   
3               0         93826.63       0                  0   
4               1         79084.10       0                  0   

   Geography_Spain  Gender_Male  
0                0            0  
1                1            0  
2                0            0  
3                0            0  
4                1            0

In [81]:
dataset_new.shape

(10000, 12)

In [82]:
dataset_new.columns

Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'Geography_Germany',
       'Geography_Spain', 'Gender_Male'],
      dtype='object')

In [83]:
dataset_new.columns.difference(['Exited'])

Index(['Age', 'Balance', 'CreditScore', 'EstimatedSalary', 'Gender_Male',
       'Geography_Germany', 'Geography_Spain', 'HasCrCard', 'IsActiveMember',
       'NumOfProducts', 'Tenure'],
      dtype='object')

In [84]:
X = dataset_new[dataset_new.columns.difference(['Exited'])]

In [85]:
y = dataset_new['Exited']

In [86]:
from sklearn.model_selection import train_test_split

In [87]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.3, random_state =123)

In [88]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
train_X = sc.fit_transform(train_X)
test_X = sc.transform(test_X)

In [89]:
train_X.shape

(7000, 11)

In [90]:
model = keras.Sequential()

In [91]:
model.add(keras.layers.Dense(6, activation = 'relu', input_shape=(train_X.shape[-1],)))
model.add(keras.layers.Dense(6, activation = 'relu'))
model.add(keras.layers.Dense(1, activation = 'sigmoid'))

In [92]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [93]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 6)                 72        
                                                                 
 dense_1 (Dense)             (None, 6)                 42        
                                                                 
 dense_2 (Dense)             (None, 1)                 7         
                                                                 
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


In [94]:
model.fit(train_X, train_y, batch_size = 20, epochs = 10)

Epoch 1/10
350/350 [==============================] - 4s 3ms/step - loss: 0.5646 - accuracy: 0.7229
Epoch 2/10
350/350 [==============================] - 1s 3ms/step - loss: 0.4585 - accuracy: 0.7963
Epoch 3/10
350/350 [==============================] - 1s 3ms/step - loss: 0.4402 - accuracy: 0.8021
Epoch 4/10
350/350 [==============================] - 1s 3ms/step - loss: 0.4249 - accuracy: 0.8117
Epoch 5/10
350/350 [==============================] - 1s 3ms/step - loss: 0.4095 - accuracy: 0.8221
Epoch 6/10
350/350 [==============================] - 1s 3ms/step - loss: 0.3933 - accuracy: 0.8334
Epoch 7/10
350/350 [==============================] - 2s 4ms/step - loss: 0.3790 - accuracy: 0.8413
Epoch 8/10
350/350 [==============================] - 2s 7ms/step - loss: 0.3683 - accuracy: 0.8446
Epoch 9/10
350/350 [==============================] - 2s 5ms/step - loss: 0.3617 - accuracy: 0.8484
Epoch 10/10
350/350 [==============================] - 1s 3ms/step - loss: 0.3573 - accuracy: 0.8519

In [95]:
y_pred = model.predict(test_X)

94/94 [==============================] - 0s 1ms/step


In [96]:
import sklearn.metrics as metrics

In [97]:
metrics.roc_auc_score(test_y, y_pred)

0.8559015856036163

In [98]:
y_pred = (y_pred > 0.2)

In [99]:
# Creating the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(test_y, y_pred)

In [100]:
print(metrics.classification_report(test_y, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.80      0.86      2395
           1       0.49      0.74      0.59       605

    accuracy                           0.79      3000
   macro avg       0.71      0.77      0.72      3000
weighted avg       0.84      0.79      0.80      3000



In [101]:
model.save('model.h5')

In [102]:
from keras.models import load_model

In [103]:
model1 = load_model('model.h5')

In [104]:
model1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 6)                 72        
                                                                 
 dense_1 (Dense)             (None, 6)                 42        
                                                                 
 dense_2 (Dense)             (None, 1)                 7         
                                                                 
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


In [105]:

checkpointbest = keras.callbacks.ModelCheckpoint(filepath='weights.hdf5', verbose=1, save_best_only=True)
model.fit(train_X, train_y, epochs=20, validation_data= (test_X, test_y), callbacks=[checkpointbest])

Epoch 1/20
211/219 [===========================>..] - ETA: 0s - loss: 0.3536 - accuracy: 0.8540
Epoch 1: val_loss improved from inf to 0.34157, saving model to weights.hdf5
219/219 [==============================] - 1s 5ms/step - loss: 0.3540 - accuracy: 0.8529 - val_loss: 0.3416 - val_accuracy: 0.8617
Epoch 2/20
212/219 [============================>.] - ETA: 0s - loss: 0.3534 - accuracy: 0.8526
Epoch 2: val_loss improved from 0.34157 to 0.34069, saving model to weights.hdf5
219/219 [==============================] - 1s 4ms/step - loss: 0.3526 - accuracy: 0.8534 - val_loss: 0.3407 - val_accuracy: 0.8640
Epoch 3/20
212/219 [============================>.] - ETA: 0s - loss: 0.3530 - accuracy: 0.8514
Epoch 3: val_loss improved from 0.34069 to 0.33967, saving model to weights.hdf5
219/219 [==============================] - 1s 6ms/step - loss: 0.3514 - accuracy: 0.8520 - val_loss: 0.3397 - val_accuracy: 0.8640
Epoch 4/20
210/219 [===========================>..] - ETA: 0s - loss: 0.3476 - a

In [106]:
model.get_weights()

[array([[-0.9553073 ,  0.1025681 ,  0.29051274, -0.8691624 , -0.15191297,
          0.4136435 ],
        [ 0.18311927, -0.09357798, -0.20317651,  0.074092  ,  0.39793155,
          0.11656596],
        [-0.0768518 ,  0.02960788,  0.06388396,  0.02973151, -0.01961462,
          0.36067155],
        [-0.08672644, -0.0045914 ,  0.06109304,  0.04230382,  0.02630983,
          0.17701362],
        [ 0.2264058 , -0.17292807, -0.11540119, -0.19290388,  0.04637978,
          0.27669528],
        [-0.42629805,  0.2973965 ,  0.10583153,  0.09044058, -0.3806932 ,
         -0.5646791 ],
        [-0.0118263 , -0.05748754, -0.17207432, -0.14602876,  0.11364111,
          0.342816  ],
        [ 0.02373155, -0.11620605,  0.171279  , -0.1968215 , -0.02438671,
         -0.09799156],
        [-0.1160514 , -0.80152047,  0.3710882 , -0.60594255,  0.00228637,
          0.5118948 ],
        [ 0.23529258, -0.31137282,  1.0816128 ,  0.06628824,  1.1219195 ,
          0.4640321 ],
        [ 0.02745094, -0.11583

In [107]:
model.save_weights('model_v2.h5')